apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: service1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        
name: service1
        imagePullPolicy: Never
        image: app:1.0.0
        ports:
containerPort: 5001