version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5173:5173"
    logging:
       driver: "fluentd"
       options:
         fluentd-address: 127.0.0.1:24224
         fluentd-async: "true"
         tag: "app"

  # api:
  #   build: https://github.com/devops-g2/api.git#main
  #   command: "dev"
  #   ports:
  #     - "8000:8000"
      

       
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/var/lib/prometheus.yml
    depends_on:
      - app
  
  grafana:
     image: grafana/grafana:latest
     container_name: grafana-container
     ports:
       - "3000:3000"
     environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin 
     depends_on:
       - prometheus 
     links:
       - prometheus:prometheus

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
     container_name: elasticsearch
     environment:
       - "discovery.type=single-node"
       - "xpack.security.enabled=false"
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     ports:
       - "9200:9200"
     ulimits:
       memlock:
         soft: -1
         hard: -1
       nofile:
         soft: 65535
         hard: 65535
     cap_add:
       - IPC_LOCK
     volumes:
       - elasticsearch-data-volume:/usr/share/elasticsearch/data

  kibana:
     image: docker.elastic.co/kibana/kibana:8.9.2
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     depends_on:
       - elasticsearch


volumes:
  elasticsearch-data-volume:
    driver: local
